### ISSUE TITLE
Encryption details?

### ISSUE THREAD

**Issue by acoleman-apc** [defuse/encutil#2]
Hello, 

When I call Key::createNewRandomKey(), I don't have the option to pass in the the size of the key in bits (e.g. 1024 vs 2048).

What is the default key size used here?  Are there plans to expand this to allow for us to set the key size?

Thanks!

**Comment by defuse** [comment]
The crypto details are described here: https://github.com/defuse/php-encryption/blob/master/docs/CryptoDetails.md. I'd advise against using this and instead recommend [age](https://github.com/FiloSottile/age) instead, since this is pretty much just an example for how to use defuse/php-encryption.

To answer your question, there won't be an option to choose the key size, since defuse/php-encryption's philosophy is to come secure by default and not expose any options like key size, cipher, etc.
